version: '3.8'

services:

    # BACKEND API
    backend-api: 
        container_name: backend
        # image: node: 12.16.1
        build: ./
        command: npm start
        working_dir: /usr/src/face-detect-api
        environment: 
            POSTGRES_URI: postgres://martin:1q2w3e4r@postgres:5432/facedetector-docker
            REDIS_URI: redis://redis:6379 
        ports:
            - '3001:3001'
        volumes: 
            - ./:/usr/src/face-detect-api
    
    # POSTGRES
    postgres:
        container_name: postgres
        build: ./postgres
        environment: 
            POSTGRES_USER: martin
            POSTGRES_PASSWORD: 1q2w3e4r
            POSTGRES_DB: facedetector-docker
            POSTGRES_HOST: postgres
        ports: 
            - '5432:5432'
    
    # REDIS
    redis:
        image: redis
        ports: 
            - '6379:6379'